// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type BlogPostDocumentDataSlicesSlice = ImageBlockSlice | BlogContentSlice;

/**
 * Content for Blog post documents
 */
interface BlogPostDocumentData {
  /**
   * Title field in *Blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Date field in *Blog post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * Hover image field in *Blog post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.hover_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hover_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Blog post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | ArtistGallerySlice
  | ContentSectionSlice
  | MobileAppInterfaceShowcaseSlice
  | IntroSlice
  | AppSlice
  | TeamSlice
  | TestimonialsSlice
  | HeroSlice
  | ServicesSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | BlogIndexSlice
  | CalendlySlice
  | ProjectsSlice
  | BookingSlice
  | StorySlice
  | TeamSlice
  | AlternateGridSlice
  | AppSlice
  | BenefitsSlice
  | BannerSlice
  | StatsSlice
  | WorksSlice
  | UserSlice
  | TestimonialsSlice
  | IntroSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Navitems*
 */
export interface SettingsDocumentDataNavitemsItem {
  /**
   * Nav Link field in *Settings → Navitems*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navitems[].nav_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  nav_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Nav Label field in *Settings → Navitems*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navitems[].nav_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nav_label: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Navitems field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navitems[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navitems: prismic.GroupField<Simplify<SettingsDocumentDataNavitemsItem>>;

  /**
   * Instagram Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.instagram_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  instagram_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * LinkedIn Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.linkedin_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  linkedin_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Facebook Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.facebook_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  facebook_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * CTA Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * CTA Label field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.cta_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | BlogPostDocument
  | HomepageDocument
  | PageDocument
  | SettingsDocument;

/**
 * Primary content in *AlternateGrid → Default → Primary*
 */
export interface AlternateGridSliceDefaultPrimary {
  /**
   * Eyebrow text field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.eyebrow_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow_text: prismic.KeyTextField;

  /**
   * Title field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Image field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * ImageOnTheRight field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: alternate_grid.default.primary.ImageOnTheRight
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  ImageOnTheRight: prismic.BooleanField;

  /**
   * CTA field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: alternate_grid.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  cta: prismic.BooleanField;

  /**
   * CTA Link field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * CTA label field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;
}

/**
 * Default variation for AlternateGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AlternateGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AlternateGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AlternateGrid*
 */
type AlternateGridSliceVariation = AlternateGridSliceDefault;

/**
 * AlternateGrid Shared Slice
 *
 * - **API ID**: `alternate_grid`
 * - **Description**: AlternateGrid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AlternateGridSlice = prismic.SharedSlice<
  "alternate_grid",
  AlternateGridSliceVariation
>;

/**
 * Primary content in *App → Default → Primary*
 */
export interface AppSliceDefaultPrimary {
  /**
   * Heading field in *App → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Heading Secondary field in *App → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app.default.primary.heading_secondary
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading_secondary: prismic.KeyTextField;

  /**
   * Subtext field in *App → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app.default.primary.subtext
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtext: prismic.KeyTextField;

  /**
   * Google store field in *App → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: app.default.primary.google_store
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  google_store: prismic.ImageField<never>;

  /**
   * Google app field in *App → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: app.default.primary.google_app
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  google_app: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Apple store field in *App → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: app.default.primary.apple_store
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  apple_store: prismic.ImageField<never>;

  /**
   * Apple App field in *App → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: app.default.primary.apple_app
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  apple_app: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *App → Items*
 */
export interface AppSliceDefaultItem {
  /**
   * Testimonial field in *App → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app.items[].testimonial
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  testimonial: prismic.KeyTextField;
}

/**
 * Default variation for App Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AppSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AppSliceDefaultPrimary>,
  Simplify<AppSliceDefaultItem>
>;

/**
 * Slice variation for *App*
 */
type AppSliceVariation = AppSliceDefault;

/**
 * App Shared Slice
 *
 * - **API ID**: `app`
 * - **Description**: App
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AppSlice = prismic.SharedSlice<"app", AppSliceVariation>;

/**
 * Primary content in *ArtistGallery → Default → Primary*
 */
export interface ArtistGallerySliceDefaultPrimary {
  /**
   * Title field in *ArtistGallery → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Meet Our Artists
   * - **API ID Path**: artist_gallery.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *ArtistGallery → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The creative minds behind OVERHEAR
   * - **API ID Path**: artist_gallery.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Background Color field in *ArtistGallery → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: artist_gallery.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_color: prismic.ColorField;
}

/**
 * Default variation for ArtistGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation for artist gallery
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ArtistGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArtistGallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ArtistGallery*
 */
type ArtistGallerySliceVariation = ArtistGallerySliceDefault;

/**
 * ArtistGallery Shared Slice
 *
 * - **API ID**: `artist_gallery`
 * - **Description**: Artist Gallery - Fetches artist data from external API
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ArtistGallerySlice = prismic.SharedSlice<
  "artist_gallery",
  ArtistGallerySliceVariation
>;

/**
 * Primary content in *Banner → Default → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * Banner Text field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.banner_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  banner_text: prismic.KeyTextField;
}

/**
 * Primary content in *Banner → Items*
 */
export interface BannerSliceDefaultItem {
  /**
   * Brand image field in *Banner → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.items[].brand_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  brand_image: prismic.ImageField<never>;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  Simplify<BannerSliceDefaultItem>
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Primary content in *Benefits → Default → Primary*
 */
export interface BenefitsSliceDefaultPrimary {
  /**
   * eyebrow text field in *Benefits → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.default.primary.eyebrow_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow_text: prismic.KeyTextField;

  /**
   * title field in *Benefits → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *Benefits → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;
}

/**
 * Primary content in *Benefits → Items*
 */
export interface BenefitsSliceDefaultItem {
  /**
   * Card Image field in *Benefits → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.items[].card_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  card_image: prismic.ImageField<never>;

  /**
   * Card Icon field in *Benefits → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.items[].card_icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  card_icon: prismic.SelectField<"first" | "second" | "third">;

  /**
   * Card Title field in *Benefits → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.items[].card_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_title: prismic.RichTextField;

  /**
   * Card Content field in *Benefits → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.items[].card_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_content: prismic.RichTextField;
}

/**
 * Default variation for Benefits Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BenefitsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BenefitsSliceDefaultPrimary>,
  Simplify<BenefitsSliceDefaultItem>
>;

/**
 * Slice variation for *Benefits*
 */
type BenefitsSliceVariation = BenefitsSliceDefault;

/**
 * Benefits Shared Slice
 *
 * - **API ID**: `benefits`
 * - **Description**: Benefits
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BenefitsSlice = prismic.SharedSlice<
  "benefits",
  BenefitsSliceVariation
>;

/**
 * Primary content in *BlogContent → Default → Primary*
 */
export interface BlogContentSliceDefaultPrimary {
  /**
   * Blog Content field in *BlogContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_content.default.primary.blog_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  blog_content: prismic.RichTextField;
}

/**
 * Default variation for BlogContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogContent*
 */
type BlogContentSliceVariation = BlogContentSliceDefault;

/**
 * BlogContent Shared Slice
 *
 * - **API ID**: `blog_content`
 * - **Description**: BlogContent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogContentSlice = prismic.SharedSlice<
  "blog_content",
  BlogContentSliceVariation
>;

/**
 * Primary content in *BlogIndex → Default → Primary*
 */
export interface BlogIndexSliceDefaultPrimary {
  /**
   * Eyebrow Text field in *BlogIndex → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_index.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *BlogIndex → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_index.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtext field in *BlogIndex → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_index.default.primary.subtext
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtext: prismic.RichTextField;

  /**
   * Fallback field in *BlogIndex → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_index.default.primary.fallback
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  fallback: prismic.ImageField<never>;
}

/**
 * Default variation for BlogIndex Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogIndexSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogIndexSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogIndex*
 */
type BlogIndexSliceVariation = BlogIndexSliceDefault;

/**
 * BlogIndex Shared Slice
 *
 * - **API ID**: `blog_index`
 * - **Description**: BlogIndex
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogIndexSlice = prismic.SharedSlice<
  "blog_index",
  BlogIndexSliceVariation
>;

/**
 * Primary content in *Booking → Default → Primary*
 */
export interface BookingSliceDefaultPrimary {
  /**
   * Eyebrow text field in *Booking → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: booking.default.primary.eyebrow_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow_text: prismic.KeyTextField;

  /**
   * Heading field in *Booking → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: booking.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * subtext field in *Booking → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: booking.default.primary.subtext
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtext: prismic.RichTextField;

  /**
   * Booking link field in *Booking → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: booking.default.primary.booking_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  booking_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Booking → Items*
 */
export interface BookingSliceDefaultItem {
  /**
   * Image field in *Booking → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: booking.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Booking Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BookingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BookingSliceDefaultPrimary>,
  Simplify<BookingSliceDefaultItem>
>;

/**
 * Slice variation for *Booking*
 */
type BookingSliceVariation = BookingSliceDefault;

/**
 * Booking Shared Slice
 *
 * - **API ID**: `booking`
 * - **Description**: Booking
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BookingSlice = prismic.SharedSlice<
  "booking",
  BookingSliceVariation
>;

/**
 * Primary content in *Calendly → Default → Primary*
 */
export interface CalendlySliceDefaultPrimary {
  /**
   * Page title field in *Calendly → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calendly.default.primary.page_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_title: prismic.KeyTextField;

  /**
   * Widget Link field in *Calendly → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: calendly.default.primary.widget_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  widget_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Calendly Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CalendlySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CalendlySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Calendly*
 */
type CalendlySliceVariation = CalendlySliceDefault;

/**
 * Calendly Shared Slice
 *
 * - **API ID**: `calendly`
 * - **Description**: Calendly
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CalendlySlice = prismic.SharedSlice<
  "calendly",
  CalendlySliceVariation
>;

/**
 * Primary content in *ContentSection → Default → Primary*
 */
export interface ContentSectionSliceDefaultPrimary {
  /**
   * Title field in *ContentSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section Title
   * - **API ID Path**: content_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *ContentSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section Subtitle
   * - **API ID Path**: content_section.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Description field in *ContentSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Section description content
   * - **API ID Path**: content_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Image field in *ContentSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Position field in *ContentSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: right
   * - **API ID Path**: content_section.default.primary.image_position
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  image_position: prismic.SelectField<
    "left" | "right" | "top" | "bottom",
    "filled"
  >;

  /**
   * Text Alignment field in *ContentSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: center
   * - **API ID Path**: content_section.default.primary.text_align
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  text_align: prismic.SelectField<"left" | "center" | "right", "filled">;

  /**
   * Background Color field in *ContentSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: transparent
   * - **API ID Path**: content_section.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_color: prismic.SelectField<
    "transparent" | "blue-900" | "gray-900" | "white",
    "filled"
  >;

  /**
   * Text Color field in *ContentSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: white
   * - **API ID Path**: content_section.default.primary.text_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  text_color: prismic.SelectField<"white" | "black" | "gray-900", "filled">;
}

/**
 * Default variation for ContentSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentSection*
 */
type ContentSectionSliceVariation = ContentSectionSliceDefault;

/**
 * ContentSection Shared Slice
 *
 * - **API ID**: `content_section`
 * - **Description**: ContentSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSectionSlice = prismic.SharedSlice<
  "content_section",
  ContentSectionSliceVariation
>;

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * Copyright Text field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: © 2024 Overhear Ltd. All rights reserved.
   * - **API ID Path**: footer.default.primary.copyright_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright_text: prismic.KeyTextField;
}

/**
 * Primary content in *Footer → Items*
 */
export interface FooterSliceDefaultItem {
  /**
   * Section Title field in *Footer → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: About
   * - **API ID Path**: footer.items[].section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Link Text field in *Footer → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Our Story
   * - **API ID Path**: footer.items[].link_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_text: prismic.KeyTextField;

  /**
   * Link field in *Footer → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: /about
   * - **API ID Path**: footer.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  Simplify<FooterSliceDefaultItem>
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Logo Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.logo_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo_image: prismic.ImageField<never>;

  /**
   * Hero Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heroimg
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  heroimg: prismic.ImageField<never>;

  /**
   * Google Play Store Badge field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.google_store
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  google_store: prismic.ImageField<never>;

  /**
   * Google Play App Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://play.google.com/store/apps/details?id=com.overhear
   * - **API ID Path**: hero.default.primary.google_app
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  google_app: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Apple App Store Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://apps.apple.com/app/overhear
   * - **API ID Path**: hero.default.primary.apple_app
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  apple_app: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Apple App Store Badge field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.apple_store
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  apple_store: prismic.ImageField<never>;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceDefaultItem {
  /**
   * Testimonial field in *Hero → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: User testimonial text
   * - **API ID Path**: hero.items[].testimonial
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  testimonial: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  Simplify<HeroSliceDefaultItem>
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ImageBlock → Default → Primary*
 */
export interface ImageBlockSliceDefaultPrimary {
  /**
   * Image field in *ImageBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_block.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageBlock*
 */
type ImageBlockSliceVariation = ImageBlockSliceDefault;

/**
 * ImageBlock Shared Slice
 *
 * - **API ID**: `image_block`
 * - **Description**: ImageBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageBlockSlice = prismic.SharedSlice<
  "image_block",
  ImageBlockSliceVariation
>;

/**
 * Primary content in *Intro → Default → Primary*
 */
export interface IntroSliceDefaultPrimary {
  /**
   * Image field in *Intro → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * image left field in *Intro → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: intro.default.primary.image_left
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  image_left: prismic.BooleanField;

  /**
   * Show Links field in *Intro → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: intro.default.primary.show_cta
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_cta: prismic.BooleanField;

  /**
   * Show Appstore Links field in *Intro → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: intro.default.primary.app_cta
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  app_cta: prismic.BooleanField;

  /**
   * Eyebrow field in *Intro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *Intro → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Content field in *Intro → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Google App field in *Intro → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.google_app
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  google_app: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Google store field in *Intro → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.google_store
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  google_store: prismic.ImageField<never>;

  /**
   * Apple app field in *Intro → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.apple_app
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  apple_app: prismic.ImageField<never>;

  /**
   * Apple Store field in *Intro → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.apple_store
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  apple_store: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Link Label field in *Intro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;

  /**
   * Link field in *Intro → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to page or website
   * - **API ID Path**: intro.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Intro Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IntroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Intro*
 */
type IntroSliceVariation = IntroSliceDefault;

/**
 * Intro Shared Slice
 *
 * - **API ID**: `intro`
 * - **Description**: Intro
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IntroSlice = prismic.SharedSlice<"intro", IntroSliceVariation>;

/**
 * Item in *MobileAppInterfaceShowcase → Default → Primary → Device Screens*
 */
export interface MobileAppInterfaceShowcaseSliceDefaultPrimaryDevicesItem {
  /**
   * Screenshot Image field in *MobileAppInterfaceShowcase → Default → Primary → Device Screens*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_app_interface_showcase.default.primary.devices[].screenshot
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  screenshot: prismic.ImageField<never>;

  /**
   * Screen Label field in *MobileAppInterfaceShowcase → Default → Primary → Device Screens*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_app_interface_showcase.default.primary.devices[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *MobileAppInterfaceShowcase → Default → Primary*
 */
export interface MobileAppInterfaceShowcaseSliceDefaultPrimary {
  /**
   * Background Color field in *MobileAppInterfaceShowcase → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_app_interface_showcase.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_color: prismic.ColorField;

  /**
   * Device Screens field in *MobileAppInterfaceShowcase → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mobile_app_interface_showcase.default.primary.devices[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  devices: prismic.GroupField<
    Simplify<MobileAppInterfaceShowcaseSliceDefaultPrimaryDevicesItem>
  >;
}

/**
 * Default variation for MobileAppInterfaceShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation presenting up to two overlapping phone mockups, each with a custom screenshot and an optional label.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MobileAppInterfaceShowcaseSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<MobileAppInterfaceShowcaseSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *MobileAppInterfaceShowcase*
 */
type MobileAppInterfaceShowcaseSliceVariation =
  MobileAppInterfaceShowcaseSliceDefault;

/**
 * MobileAppInterfaceShowcase Shared Slice
 *
 * - **API ID**: `mobile_app_interface_showcase`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MobileAppInterfaceShowcaseSlice = prismic.SharedSlice<
  "mobile_app_interface_showcase",
  MobileAppInterfaceShowcaseSliceVariation
>;

/**
 * Primary content in *Projects → Default → Primary*
 */
export interface ProjectsSliceDefaultPrimary {
  /**
   * Eyebrow text field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.eyebrow_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow_text: prismic.KeyTextField;

  /**
   * Title field in *Projects → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtext field in *Projects → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.subtext
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtext: prismic.RichTextField;
}

/**
 * Primary content in *Projects → Items*
 */
export interface ProjectsSliceDefaultItem {
  /**
   * image field in *Projects → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Project title field in *Projects → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.items[].project_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_title: prismic.KeyTextField;

  /**
   * Project description field in *Projects → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.items[].project_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_description: prismic.RichTextField;
}

/**
 * Default variation for Projects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectsSliceDefaultPrimary>,
  Simplify<ProjectsSliceDefaultItem>
>;

/**
 * Slice variation for *Projects*
 */
type ProjectsSliceVariation = ProjectsSliceDefault;

/**
 * Projects Shared Slice
 *
 * - **API ID**: `projects`
 * - **Description**: Projects
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectsSlice = prismic.SharedSlice<
  "projects",
  ProjectsSliceVariation
>;

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
  /**
   * Title field in *Services → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Services
   * - **API ID Path**: services.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Services → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Explore our innovative audio delivery technology that brings stories, poetry and oral histories to life through geolocation and/or QR codes.
   * - **API ID Path**: services.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * Primary content in *Services → Items*
 */
export interface ServicesSliceDefaultItem {
  /**
   * Service Title field in *Services → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Geo-Location & QR
   * - **API ID Path**: services.items[].service_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  service_title: prismic.KeyTextField;

  /**
   * Service Description field in *Services → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Collect audio on location using geolocation or QR codes. Explore your surroundings to discover audio linked to specific places.
   * - **API ID Path**: services.items[].service_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  service_description: prismic.KeyTextField;

  /**
   * Service Image field in *Services → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.items[].service_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  service_image: prismic.ImageField<never>;

  /**
   * Service Icon (emoji) field in *Services → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 🎧
   * - **API ID Path**: services.items[].service_icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  service_icon: prismic.KeyTextField;

  /**
   * Service Secondary Image field in *Services → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.items[].service_secondary_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  service_secondary_image: prismic.ImageField<never>;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSliceDefaultPrimary>,
  Simplify<ServicesSliceDefaultItem>
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSlice = prismic.SharedSlice<
  "services",
  ServicesSliceVariation
>;

/**
 * Primary content in *Stats → Items*
 */
export interface StatsSliceDefaultItem {
  /**
   * Name field in *Stats → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats.items[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Value field in *Stats → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats.items[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;
}

/**
 * Default variation for Stats Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<StatsSliceDefaultItem>
>;

/**
 * Slice variation for *Stats*
 */
type StatsSliceVariation = StatsSliceDefault;

/**
 * Stats Shared Slice
 *
 * - **API ID**: `stats`
 * - **Description**: Stats
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatsSlice = prismic.SharedSlice<"stats", StatsSliceVariation>;

/**
 * Primary content in *Story → Default → Primary*
 */
export interface StorySliceDefaultPrimary {
  /**
   * Eyebrow text field in *Story → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story.default.primary.eyebrow_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow_text: prismic.KeyTextField;

  /**
   * Heading field in *Story → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Subtext field in *Story → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story.default.primary.subtext
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtext: prismic.RichTextField;
}

/**
 * Primary content in *Story → Items*
 */
export interface StorySliceDefaultItem {
  /**
   * Milestone field in *Story → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story.items[].milestone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  milestone: prismic.KeyTextField;

  /**
   * Title field in *Story → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Date field in *Story → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story.items[].date
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  date: prismic.KeyTextField;

  /**
   * Summary field in *Story → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story.items[].summary
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  summary: prismic.RichTextField;
}

/**
 * Default variation for Story Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StorySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StorySliceDefaultPrimary>,
  Simplify<StorySliceDefaultItem>
>;

/**
 * Slice variation for *Story*
 */
type StorySliceVariation = StorySliceDefault;

/**
 * Story Shared Slice
 *
 * - **API ID**: `story`
 * - **Description**: Story
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StorySlice = prismic.SharedSlice<"story", StorySliceVariation>;

/**
 * Primary content in *Team → Default → Primary*
 */
export interface TeamSliceDefaultPrimary {
  /**
   * Eyebrow field in *Team → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *Team → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Subtext field in *Team → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.subtext
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtext: prismic.RichTextField;
}

/**
 * Primary content in *Team → Items*
 */
export interface TeamSliceDefaultItem {
  /**
   * Profile Image field in *Team → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].profile_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  profile_image: prismic.ImageField<never>;

  /**
   * Full name field in *Team → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].full_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  full_name: prismic.KeyTextField;

  /**
   * Role field in *Team → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * Bio field in *Team → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].bio
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bio: prismic.RichTextField;

  /**
   * LinkedIn Url field in *Team → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].linkedin_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  linkedin_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * twitter url field in *Team → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].twitter_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  twitter_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSliceDefaultPrimary>,
  Simplify<TeamSliceDefaultItem>
>;

/**
 * Slice variation for *Team*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamSlice = prismic.SharedSlice<"team", TeamSliceVariation>;

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Eyebrow text field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.eyebrow_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow_text: prismic.KeyTextField;

  /**
   * Title field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * Primary content in *Testimonials → Items*
 */
export interface TestimonialsSliceDefaultItem {
  /**
   * Name field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Testimonial field in *Testimonials → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].testimonial
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonial: prismic.RichTextField;

  /**
   * Header Type field in *Testimonials → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: quotes
   * - **API ID Path**: testimonials.items[].header_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  header_type: prismic.SelectField<"quotes" | "stars", "filled">;

  /**
   * Background Type field in *Testimonials → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: white
   * - **API ID Path**: testimonials.items[].background_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_type: prismic.SelectField<"white" | "image", "filled">;

  /**
   * Background Image field in *Testimonials → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  Simplify<TestimonialsSliceDefaultItem>
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Primary content in *User → Default → Primary*
 */
export interface UserSliceDefaultPrimary {
  /**
   * User Image field in *User → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: user.default.primary.user_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  user_image: prismic.ImageField<never>;

  /**
   * Testimonial field in *User → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: user.default.primary.testimonial
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonial: prismic.RichTextField;

  /**
   * Name field in *User → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: user.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;
}

/**
 * Default variation for User Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type UserSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<UserSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *User*
 */
type UserSliceVariation = UserSliceDefault;

/**
 * User Shared Slice
 *
 * - **API ID**: `user`
 * - **Description**: User
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type UserSlice = prismic.SharedSlice<"user", UserSliceVariation>;

/**
 * Primary content in *Works → Default → Primary*
 */
export interface WorksSliceDefaultPrimary {
  /**
   * Video field in *Works → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: works.default.primary.video
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Video left field in *Works → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: works.default.primary.video_left
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  video_left: prismic.BooleanField;

  /**
   * Show links field in *Works → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: works.default.primary.show_links
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_links: prismic.BooleanField;

  /**
   * Show app store links field in *Works → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: works.default.primary.app_cta
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  app_cta: prismic.BooleanField;

  /**
   * Video preview image field in *Works → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: works.default.primary.preview_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  preview_image: prismic.ImageField<never>;

  /**
   * Eyebrow field in *Works → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *Works → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * content field in *Works → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Google app field in *Works → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: works.default.primary.google_app
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  google_app: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Google store field in *Works → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: works.default.primary.google_store
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  google_store: prismic.ImageField<never>;

  /**
   * Apple app field in *Works → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: works.default.primary.apple_app
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  apple_app: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Apple store field in *Works → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: works.default.primary.apple_store
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  apple_store: prismic.ImageField<never>;

  /**
   * Link label field in *Works → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works.default.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;

  /**
   * Link field in *Works → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: works.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Works Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WorksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorksSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Works*
 */
type WorksSliceVariation = WorksSliceDefault;

/**
 * Works Shared Slice
 *
 * - **API ID**: `works`
 * - **Description**: Works
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WorksSlice = prismic.SharedSlice<"works", WorksSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavitemsItem,
      AllDocumentTypes,
      AlternateGridSlice,
      AlternateGridSliceDefaultPrimary,
      AlternateGridSliceVariation,
      AlternateGridSliceDefault,
      AppSlice,
      AppSliceDefaultPrimary,
      AppSliceDefaultItem,
      AppSliceVariation,
      AppSliceDefault,
      ArtistGallerySlice,
      ArtistGallerySliceDefaultPrimary,
      ArtistGallerySliceVariation,
      ArtistGallerySliceDefault,
      BannerSlice,
      BannerSliceDefaultPrimary,
      BannerSliceDefaultItem,
      BannerSliceVariation,
      BannerSliceDefault,
      BenefitsSlice,
      BenefitsSliceDefaultPrimary,
      BenefitsSliceDefaultItem,
      BenefitsSliceVariation,
      BenefitsSliceDefault,
      BlogContentSlice,
      BlogContentSliceDefaultPrimary,
      BlogContentSliceVariation,
      BlogContentSliceDefault,
      BlogIndexSlice,
      BlogIndexSliceDefaultPrimary,
      BlogIndexSliceVariation,
      BlogIndexSliceDefault,
      BookingSlice,
      BookingSliceDefaultPrimary,
      BookingSliceDefaultItem,
      BookingSliceVariation,
      BookingSliceDefault,
      CalendlySlice,
      CalendlySliceDefaultPrimary,
      CalendlySliceVariation,
      CalendlySliceDefault,
      ContentSectionSlice,
      ContentSectionSliceDefaultPrimary,
      ContentSectionSliceVariation,
      ContentSectionSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimary,
      FooterSliceDefaultItem,
      FooterSliceVariation,
      FooterSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefaultItem,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageBlockSlice,
      ImageBlockSliceDefaultPrimary,
      ImageBlockSliceVariation,
      ImageBlockSliceDefault,
      IntroSlice,
      IntroSliceDefaultPrimary,
      IntroSliceVariation,
      IntroSliceDefault,
      MobileAppInterfaceShowcaseSlice,
      MobileAppInterfaceShowcaseSliceDefaultPrimaryDevicesItem,
      MobileAppInterfaceShowcaseSliceDefaultPrimary,
      MobileAppInterfaceShowcaseSliceVariation,
      MobileAppInterfaceShowcaseSliceDefault,
      ProjectsSlice,
      ProjectsSliceDefaultPrimary,
      ProjectsSliceDefaultItem,
      ProjectsSliceVariation,
      ProjectsSliceDefault,
      ServicesSlice,
      ServicesSliceDefaultPrimary,
      ServicesSliceDefaultItem,
      ServicesSliceVariation,
      ServicesSliceDefault,
      StatsSlice,
      StatsSliceDefaultItem,
      StatsSliceVariation,
      StatsSliceDefault,
      StorySlice,
      StorySliceDefaultPrimary,
      StorySliceDefaultItem,
      StorySliceVariation,
      StorySliceDefault,
      TeamSlice,
      TeamSliceDefaultPrimary,
      TeamSliceDefaultItem,
      TeamSliceVariation,
      TeamSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceDefaultItem,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      UserSlice,
      UserSliceDefaultPrimary,
      UserSliceVariation,
      UserSliceDefault,
      WorksSlice,
      WorksSliceDefaultPrimary,
      WorksSliceVariation,
      WorksSliceDefault,
    };
  }
}
