// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_grid: dynamic(() => import("./AlternateGrid")),
  app: dynamic(() => import("./App")),
  banner: dynamic(() => import("./Banner")),
  benefits: dynamic(() => import("./Benefits")),
  booking: dynamic(() => import("./Booking")),
  hero: dynamic(() => import("./Hero")),
  intro: dynamic(() => import("./Intro")),
  stats: dynamic(() => import("./Stats")),
  story: dynamic(() => import("./Story")),
  team: dynamic(() => import("./Team")),
  testimonials: dynamic(() => import("./Testimonials")),
  user: dynamic(() => import("./User")),
  works: dynamic(() => import("./Works")),
};
